ARG DEV_IMAGE=linear-app
FROM ${DEV_IMAGE}

COPY deps.edn bb.edn ./
COPY src ./src
COPY resources ./resources
COPY config ./config
COPY migrations.edn ./
COPY duct.gcp.edn ./duct.edn

CMD ["clojure", "-M:duct", "--main"]
